import requests
import argparse
from bs4 import BeautifulSoup

version = "0.1.0";

print(f"Running lang {version}")

def write_to_file(url, range_num, file_name, file_attr):
     file = open(file_name, file_attr, encoding='utf-8')
     for x in range(range_num + 1):
         final_url = url + str(x)
         print(f"Scraping {final_url}")
         r = requests.get(final_url, headers={'user-agent': 'Mozilla/5.0'})
         soup = BeautifulSoup(r.content, 'html5lib')
         for foo in soup.find_all('div'):
             if(foo['class'][0] == 'entries'):
                 if(foo.find('ul')):
                     text = foo.text.encode('utf-8')
                     mod_text = text.decode('utf-8').replace('                                        ', '').replace('                    \n', '').replace('              \n', '').replace('    \n', '').replace('    ', '').strip()
                     file.write(mod_text + "\n")
                     print(mod_text)
     file.close()

write_to_file('https://www.merriam-webster.com/browse/dictionary/0/', 1, 'Base-Dict.txt', 'w')
write_to_file('https://www.merriam-webster.com/browse/dictionary/a/', 76, 'Base-Dict.txt', 'a')
write_to_file('https://www.merriam-webster.com/browse/dictionary/b/', 76, 'Base-Dict.txt', 'a')
write_to_file('https://www.merriam-webster.com/browse/dictionary/c/', 113, 'Base-Dict.txt', 'a')
write_to_file('https://www.merriam-webster.com/browse/dictionary/d/', 60, 'Base-Dict.txt', 'a')
write_to_file('https://www.merriam-webster.com/browse/dictionary/e/', 39, 'Base-Dict.txt', 'a')
write_to_file('https://www.merriam-webster.com/browse/dictionary/f/', 48, 'Base-Dict.txt', 'a')
write_to_file('https://www.merriam-webster.com/browse/dictionary/g/', 43, 'Base-Dict.txt', 'a')
write_to_file('https://www.merriam-webster.com/browse/dictionary/h/', 48, 'Base-Dict.txt', 'a')
write_to_file('https://www.merriam-webster.com/browse/dictionary/i/', 38, 'Base-Dict.txt', 'a')
write_to_file('https://www.merriam-webster.com/browse/dictionary/j/', 12, 'Base-Dict.txt', 'a')
write_to_file('https://www.merriam-webster.com/browse/dictionary/k/', 17, 'Base-Dict.txt', 'a')
write_to_file('https://www.merriam-webster.com/browse/dictionary/l/', 40, 'Base-Dict.txt', 'a')
write_to_file('https://www.merriam-webster.com/browse/dictionary/m/', 65, 'Base-Dict.txt', 'a')
write_to_file('https://www.merriam-webster.com/browse/dictionary/n/', 30, 'Base-Dict.txt', 'a')
write_to_file('https://www.merriam-webster.com/browse/dictionary/o/', 33, 'Base-Dict.txt', 'a')
write_to_file('https://www.merriam-webster.com/browse/dictionary/p/', 103, 'Base-Dict.txt', 'a')
write_to_file('https://www.merriam-webster.com/browse/dictionary/q/', 6, 'Base-Dict.txt', 'a')
write_to_file('https://www.merriam-webster.com/browse/dictionary/r/', 56, 'Base-Dict.txt', 'a')
write_to_file('https://www.merriam-webster.com/browse/dictionary/s/', 139, 'Base-Dict.txt', 'a')
write_to_file('https://www.merriam-webster.com/browse/dictionary/t/', 68, 'Base-Dict.txt', 'a')
write_to_file('https://www.merriam-webster.com/browse/dictionary/u/', 28, 'Base-Dict.txt', 'a')
write_to_file('https://www.merriam-webster.com/browse/dictionary/v/', 17, 'Base-Dict.txt', 'a')
write_to_file('https://www.merriam-webster.com/browse/dictionary/w/', 33, 'Base-Dict.txt', 'a')
write_to_file('https://www.merriam-webster.com/browse/dictionary/x/', 2, 'Base-Dict.txt', 'a')
write_to_file('https://www.merriam-webster.com/browse/dictionary/y/', 6, 'Base-Dict.txt', 'a')
write_to_file('https://www.merriam-webster.com/browse/dictionary/z/', 5, 'Base-Dict.txt', 'a')
write_to_file('https://www.merriam-webster.com/browse/thesaurus/0/', 1, 'Base-Theasaurus.txt', 'w')
write_to_file('https://www.merriam-webster.com/browse/thesaurus/a/', 39, 'Base-Theasaurus.txt', 'a')
write_to_file('https://www.merriam-webster.com/browse/thesaurus/b/', 47, 'Base-Theasaurus.txt', 'a')
write_to_file('https://www.merriam-webster.com/browse/thesaurus/c/', 76, 'Base-Theasaurus.txt', 'a')
write_to_file('https://www.merriam-webster.com/browse/thesaurus/d/', 51, 'Base-Theasaurus.txt', 'a')
write_to_file('https://www.merriam-webster.com/browse/thesaurus/e/', 30, 'Base-Theasaurus.txt', 'a')
write_to_file('https://www.merriam-webster.com/browse/thesaurus/f/', 34, 'Base-Theasaurus.txt', 'a')
write_to_file('https://www.merriam-webster.com/browse/thesaurus/g/', 27, 'Base-Theasaurus.txt', 'a')
write_to_file('https://www.merriam-webster.com/browse/thesaurus/h/', 30, 'Base-Theasaurus.txt', 'a')
write_to_file('https://www.merriam-webster.com/browse/thesaurus/i/', 32, 'Base-Theasaurus.txt', 'a')
write_to_file('https://www.merriam-webster.com/browse/thesaurus/j/', 7, 'Base-Theasaurus.txt', 'a')
write_to_file('https://www.merriam-webster.com/browse/thesaurus/k/', 8, 'Base-Theasaurus.txt', 'a')
write_to_file('https://www.merriam-webster.com/browse/thesaurus/l/', 24, 'Base-Theasaurus.txt', 'a')
write_to_file('https://www.merriam-webster.com/browse/thesaurus/m/', 36, 'Base-Theasaurus.txt', 'a')
write_to_file('https://www.merriam-webster.com/browse/thesaurus/n/', 16, 'Base-Theasaurus.txt', 'a')
write_to_file('https://www.merriam-webster.com/browse/thesaurus/o/', 18, 'Base-Theasaurus.txt', 'a')
write_to_file('https://www.merriam-webster.com/browse/thesaurus/p/', 55, 'Base-Theasaurus.txt', 'a')
write_to_file('https://www.merriam-webster.com/browse/thesaurus/q/', 4, 'Base-Theasaurus.txt', 'a')
write_to_file('https://www.merriam-webster.com/browse/thesaurus/r/', 46, 'Base-Theasaurus.txt', 'a')
write_to_file('https://www.merriam-webster.com/browse/thesaurus/s/', 87, 'Base-Theasaurus.txt', 'a')
write_to_file('https://www.merriam-webster.com/browse/thesaurus/t/', 36, 'Base-Theasaurus.txt', 'a')
write_to_file('https://www.merriam-webster.com/browse/thesaurus/u/', 22, 'Base-Theasaurus.txt', 'a')
write_to_file('https://www.merriam-webster.com/browse/thesaurus/v/', 10, 'Base-Theasaurus.txt', 'a')
write_to_file('https://www.merriam-webster.com/browse/thesaurus/w/', 21, 'Base-Theasaurus.txt', 'a')
write_to_file('https://www.merriam-webster.com/browse/thesaurus/x/', 1, 'Base-Theasaurus.txt', 'a')
write_to_file('https://www.merriam-webster.com/browse/thesaurus/y/', 3, 'Base-Theasaurus.txt', 'a')
write_to_file('https://www.merriam-webster.com/browse/thesaurus/z/', 2, 'Base-Theasaurus.txt', 'a')